kind: pipeline
name: build

steps:
- name: test
  image: alpine:3.8
  commands:
  - echo hello
  - echo world
  - echo Hayden

- name: test2 
  image: busybox
  commands:
  - cat /etc/fstab

- name: build
  image: plugins/docker
  settings:
    dry_run: true
    repo: foo/bar
    tags: latest
  when:
    status: [ failure ]
