kind: pipeline
name: build

steps:
- name: test
  image: alpine:3.8
  commands:
  - echo hello
  - echo world
  - echo Hayden

- name: trigger
  commands:
  - echo Staring ...
  - echo OOPS .. stop

- name: build
  image: plugins/docker
  settings:
    dry_run: true
    repo: foo/bar
    tags: latest
  when:
    status: [ failure ]
